# This dockerfile builds an image that runs cUrl
FROM ubuntu:latest
RUN apt-get update && apt-get install -y curl
#[HOST[:PORT_NUMBER]/]PATH[:TAG] - usual image tags - https://docs.docker.com/get-started/docker-concepts/building-images/build-tag-and-publish-an-image/
